version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    depends_on:
      - redis
    volumes:
      - ../logs:/app/logs
      - ../media:/app/media
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    env_file:
      - docker.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ../monitoring/grafana_dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

volumes:
  redis_data:
  prometheus_data:
  grafana_data: 